"""
Stage 3c: Q-equivalence of quartics = GL2(Z) plus the scaling moves.

For M = diag(n,1) with the det^-2 normalisation, g -> n^-2 g(nu, v) sends
    (a,b,c,d,e) -> (a n^2, b n, c, d/n, e/n^2)
and the inverse sends
    (a,b,c,d,e) -> (a/n^2, b/n, c, d n, e n^2).
Both fix I and J (checked below).  Integral quartics related by these are
the SAME 2-covering, so they must be identified before counting Sel_2.
"""
from quartic import I_inv, J_inv
from equiv import act, GENS, els, has_rational_point
from enumerate_q import enumerate_quartics
import random

def scale_down(g, n):
    a,b,c,d,e = g
    if a % (n*n) or b % n: return None
    return (a//(n*n), b//n, c, d*n, e*n*n)

def scale_up(g, n):
    a,b,c,d,e = g
    if d % n or e % (n*n): return None
    return (a*n*n, b*n, c, d//n, e//(n*n))

# ---- verify the scaling moves really preserve I and J --------------------
random.seed(4); bad = 0; tested = 0
for _ in range(4000):
    g = tuple(random.randint(-20,20) for _ in range(5))
    for n in (2,3,5):
        for f in (scale_down, scale_up):
            h = f(g, n)
            if h is None: continue
            tested += 1
            if I_inv(*h) != I_inv(*g) or J_inv(*h) != J_inv(*g): bad += 1
print(f"  scaling moves tested: {tested},  invariant failures: {bad}")
assert bad == 0

def size(g): return sum(x*x for x in g)

def canonical_Q(g, beam=60, rounds=40, primes=(2,3,5,7)):
    """Beam search over the group generated by GL2(Z) AND the scalings."""
    frontier = {tuple(g)}; best = {tuple(g)}; bs = size(g)
    for it in range(rounds):
        nxt = set()
        for h in frontier:
            for M in GENS: nxt.add(act(h, M))
            for n in primes:
                for f in (scale_down, scale_up):
                    k = f(h, n)
                    if k is not None: nxt.add(k)
        pool = sorted(nxt | best, key=lambda q: (size(q), q))[:beam]
        nb = size(pool[0])
        if nb < bs: bs = nb; best = set(pool); frontier = set(pool)
        else:
            best |= {p for p in pool if size(p) == bs}
            frontier = set(pool)
            if it > 10: break
    return min([h for h in best if size(h) == bs])

if __name__ == "__main__":
    for lbl,(I,J),exp in [('37a1',(48,-432),1),('389a1',(112,-1712),2),('5077a1',(336,-10800),3)]:
        qs = enumerate_quartics(I,J)
        cls = {}
        for g in qs: cls.setdefault(canonical_Q(g), []).append(g)
        good, unk = [], []
        for k in cls:
            e = els(k, I, J)
            if e is True: good.append(k)
            elif e is None: unk.append(k)
        n = len(good)
        pw = (n & (n-1)) == 0 and n > 0
        print(f"\n  {lbl}: I={I} J={J}")
        print(f"    quartics {len(qs)} -> Q-classes {len(cls)} -> ELS {n} (inconclusive {unk and len(unk) or 0})")
        for k in sorted(good):
            print(f"      {k}   pt={has_rational_point(k)}")
        print(f"    expected 2^{exp} = {2**exp}   got {n}   "
              f"{'power of 2' if pw else 'NOT A POWER OF 2 -- still wrong'}   "
              f"{'PASS' if n == 2**exp else 'FAIL'}")
